const frame=document.querySelector('#game'),out=document.querySelector('#result'),w=()=>frame.contentWindow,d=()=>frame.contentDocument,s=()=>w().gameStatus?.();let reports=[],errors=[],held=new Set();
const wait=ms=>new Promise(r=>setTimeout(r,ms));function show(status='running',extra={}){out.textContent=JSON.stringify({status,reports,errors,...extra},null,2);}function check(ok,name,data={}){if(!ok)throw Error(name);reports.push({name,...data});show();}
async function until(fn,ms=15000){const end=performance.now()+ms;while(!fn()){if(performance.now()>end)throw Error('Timeout '+fn);await wait(30);}}
function key(code,down=true){w().dispatchEvent(new(w().KeyboardEvent)(down?'keydown':'keyup',{code,bubbles:true,cancelable:true}));}
function action(){key('KeyE');key('KeyE',false);}const click=id=>d().getElementById(id).click(),visible=()=>!d().getElementById('partResultOverlay').hidden;
async function load(street=false){reports=[];errors=[];show();frame.style.width=street?'1100px':'844px';frame.style.height=street?'690px':'390px';frame.src=(street?'./play.html':'./play.html')+'?t='+performance.now();await new Promise(r=>frame.addEventListener('load',r,{once:true}));await until(()=>s()&&!d().getElementById('startBtn').disabled);w().addEventListener('error',e=>errors.push(e.message));w().addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));click('startBtn');await until(()=>!s().dialogue&&!s().movementLocked);}
async function run(fn){try{await fn();check(errors.length===0,'브라우저 오류 없음');show('passed',{state:s()});}catch(e){show('failed',{error:e.message,state:s()});}}
async function fixtureEnd(){await until(()=>s().nearest==='test'&&!s().movementLocked);action();await until(()=>!!d().getElementById('experimentAction'));click('experimentAction');}
async function checkWaiting(){const before=s(),time=before.timer.elapsedMs,pos=before.position;key('KeyW');key('KeyE');await wait(450);key('KeyW',false);key('KeyE',false);check(s().timer.elapsedMs===time,'결과 대기시간 제외');check(s().position.x===pos.x&&s().position.z===pos.z&&s().movementLocked,'이동/행동 입력 차단');check(s().chapterId===before.chapterId&&s().questId===before.questId,'확인 전 자동 퀘스트/챕터 전환 없음');const r=d().querySelector('.part-result-card').getBoundingClientRect(),b=d().getElementById('nextPartBtn').getBoundingClientRect();check(r.left>=0&&r.right<=w().innerWidth&&b.bottom<=w().innerHeight&&b.height>=44,'화면 안 결과 및 터치 버튼 배치',{width:w().innerWidth,height:w().innerHeight,buttonHeight:b.height});}
document.querySelector('#fixture').onclick=()=>run(async()=>{
 await load();const values=[500,830,670,745,890],ids=['shutter','sorting','office','dispatch','management'];let total=0;
 for(let i=0;i<ids.length;i++){
  if(i===3){await until(()=>s().chapterId==='unscored');await fixtureEnd();await until(()=>s().chapterId==='two');check(!visible(),'무점수 기차 대역은 결과 없이 진행');}
  await until(()=>s().questId===ids[i]);await fixtureEnd();await until(visible);total+=values[i];check(d().getElementById('partResultScore').textContent.replaceAll(',','')===String(values[i]),'기존 계산 점수 표시',{id:ids[i],score:values[i]});check(d().getElementById('partResultTotal').textContent.replaceAll(',','')===total+'점','누적 점수 일치',{total});await checkWaiting();
  if(i===0){
   Object.defineProperty(d(),'hidden',{configurable:true,value:true});d().dispatchEvent(new(w().Event)('visibilitychange'));click('nextPartBtn');check(visible()&&s().timer.pauseReasons.includes('background'),'백그라운드 중 결과 확인 차단');
   delete d().hidden;d().dispatchEvent(new(w().Event)('visibilitychange'));click('nextPartBtn');check(visible(),'복귀 후 일시정지 먼저 해제 필요');click('continueBtn');check(visible()&&s().timer.pauseReasons.join(',')==='part-result'&&s().timer.interrupted,'복귀 후에도 결과 대기와 중단 이력 유지');
   key('Space');key('Space',false);
  }
  const next=d().getElementById('nextPartBtn');next.click();next.click();await until(()=>!visible());
  if(i===3){await until(()=>s().questId==='management');check(s().chapterId==='two','같은 챕터의 독립 파트도 개별 확인');}
 }
 await until(()=>s().finished);check(d().querySelectorAll('#roundResults .score-row').length===5,'엔딩에 5개 파트 점수 표시');check(w().experimentResult.total===total,'엔딩 총점과 결과 누적 점수 일치',{total});check(s().timer.pauseReasons.length===0,'확인 후 결과 일시정지 해제');click('restartBtn');await until(()=>s().questId==='shutter'&&!s().finished&&!s().movementLocked);await fixtureEnd();await until(visible);check(d().getElementById('partResultTotal').textContent==='500점','재시작 시 이전 점수 누적 안 됨');
});
async function walk(x,z){const end=performance.now()+16000;while(Math.hypot(x-s().position.x,z-s().position.z)>.17){const p=s().position,y=s().camera.currentYaw,dx=x-p.x,dz=z-p.z,ix=dx*Math.cos(y)-dz*Math.sin(y),iz=dx*Math.sin(y)+dz*Math.cos(y),m=Math.max(Math.abs(ix),Math.abs(iz));if(performance.now()>end)throw Error('Walk blocked');const next=new Set([...(Math.abs(ix)>m*.4?[ix>0?'KeyD':'KeyA']:[]),...(Math.abs(iz)>m*.4?[iz>0?'KeyS':'KeyW']:[]),'ShiftLeft']);for(const k of held)if(!next.has(k))key(k,false);for(const k of next)key(k);held=next;await wait(30);}for(const k of held)key(k,false);held.clear();await wait(150);}
document.querySelector('#street').onclick=()=>run(async()=>{await load(true);await until(()=>s().nearest==='shopkeeper');action();await until(()=>s().questId==='shutter'&&!s().dialogue);await walk(0,.65);await until(()=>s().nearest==='shutter');action();await until(visible,18000);check(w().streetStatus().shutter.closed,'실제 셔터 완전 닫힘/종료 대사 후 결과');const expected=Math.round(s().minigameResult.metrics.survivedMs/15000*1000);check(d().getElementById('partResultScore').textContent===String(expected),'실제 셔터 점수 그대로 표시',{expected});await checkWaiting();click('nextPartBtn');click('nextPartBtn');await until(()=>s().sceneId==='warehouse-workflow'&&!s().dialogue,18000);check(s().chapterIndex===1,'확인 후 최신 물류창고 한 번만 진입');check(!visible()&&!s().timer.pauseReasons.includes('part-result'),'전환 후 결과 UI/일시정지 정상 해제');check(w().chapterAudioStatus().route==='warehouse','창고 오디오 라우팅');check(w().inboundInspect().truck===10,'시작 입고 상자 10개',{inbound:w().inboundInspect()});check(s().camera.distance===3.8&&s().camera.height===1.4&&s().camera.fov===60,'창고 공통 카메라');check(!d().querySelector('.camera-tools'),'수동 카메라 UI 없음');check(w().warehouseAudioStatus().bgmReady>=2,'창고 BGM 로딩',{audio:w().warehouseAudioStatus()});});
document.querySelector('#photo').onclick=()=>run(async()=>{await load();await fixtureEnd();await until(visible);});

document.querySelector('#fixture').onclick=()=>run(async()=>{
 reports=[];errors=[];
 for(const n of [0,1,2,3,4,5]){
  frame.style.width=n===2?'844px':'1100px';frame.style.height=n===2?'390px':'690px';frame.src='./play.html?chapter='+n;await new Promise(r=>frame.addEventListener('load',r,{once:true}));await until(()=>s()&&!d().getElementById('startBtn').disabled);click('startBtn');await until(()=>s().started&&s().sceneId!=='legacy-room');await wait(650);
  const c=s().camera;if(n===3){check(c.mode==='fixed'&&s().movementLocked,'기차 전용 컷신 카메라 보존');continue;}check(c.distance===3.8&&c.pitch===Math.PI/12&&c.height===1.4&&c.fov===60,'챕터 공통 기본값',{scene:s().sceneId,camera:c});check(!d().querySelector('.camera-tools'),'카메라 프리셋 UI 제거');
  const before=JSON.stringify(s().camera);d().getElementById('scene').dispatchEvent(new(w().WheelEvent)('wheel',{deltaY:800,bubbles:true}));key('KeyQ');key('KeyQ',false);key('KeyR');key('KeyR',false);check(s().camera.distance===3.8&&s().camera.yaw===c.yaw,'휠과 Q/R로 시점 변경 안 됨');
  if(n!==3){await until(()=>!s().movementLocked);const canvas=d().getElementById('scene');canvas.setPointerCapture=()=>{};canvas.hasPointerCapture=()=>false;canvas.releasePointerCapture=()=>{};for(const [type,x,y] of [['pointerdown',500,200],['pointermove',540,230],['pointerup',540,230]])canvas.dispatchEvent(new(w().PointerEvent)(type,{pointerId:1,pointerType:n===2?'touch':'mouse',clientX:x,clientY:y,bubbles:true}));check(s().camera.yaw!==c.yaw&&s().camera.pitch!==c.pitch,'상하좌우 드래그 회전');}
 }
});
document.querySelector('#photo').textContent='입고 공급 간단 검사';
document.querySelector('#photo').onclick=()=>run(async()=>{reports=[];errors=[];frame.src='./play.html?chapter=1';await new Promise(r=>frame.addEventListener('load',r,{once:true}));await until(()=>s()&&!d().getElementById('startBtn').disabled);click('startBtn');await until(()=>!s().movementLocked);check(w().inboundInspect().truck===10,'입고 재고10');action();await until(()=>s().content?.kind==='sorting');const start=s().content.inbound.manifest;await until(()=>s().content.inbound.workerId!==null,4000);check(s().content.inbound.truck===9,'작업자가 첫 상자 운반/재고9');const id=s().content.inbound.workerId,color=s().content.inbound.workerColor;await until(()=>s().content.boxes.some(b=>b.id===id&&b.state==='moving'),4000);check(s().content.boxes.find(b=>b.id===id).color===color,'같은 ID 색상으로 컨베이어 전달');check(JSON.stringify(s().content.inbound.manifest)===JSON.stringify(start),'배정 고정');check(w().warehouseAudioStatus().bgmTime>0&&w().warehouseAudioStatus().loaded.length===4,'Scaling Up 재생 및 효과음4개 준비',{audio:w().warehouseAudioStatus()});});
