import '../experiments/register.js';
import {startGame} from '../src/runtime.js';
import {createSession} from '../experiments/scoring.js';
import {GameplayCamera} from '../src/systems/gameplay-camera.js';
import {createChapterAudio} from '../street-study/audio-routing.js';
import {spaces} from '../src/content/registry.js';
const original=spaces.get('life-office'),create=original.create;
original.create=ctx=>{const v=create(ctx);window.officeView=v;return v;};
const set=(s,t)=>document.querySelector(s).textContent=t;
document.title='2019 사무실 · 로컬 검증';set('#welcome .year','2019');set('#welcome .lead','남겨진 서류, 다음 길로 향하는 문.');set('#welcome .playtime','2019 사무실 로컬 테스트');set('#welcome .intro-note','상징적 미니게임입니다. 실제 세무조사 절차를 재현하지 않습니다.');
const scores=await fetch(new URL('../experiments/data/scores.json',import.meta.url)).then(r=>r.json());
await startGame({campaignUrl:new URL('./campaign.json',import.meta.url),session:createSession(scores,{full:false,storageKey:'office-local-test'}),cameraRig:new GameplayCamera(),audioFactory:createChapterAudio});
