const frame=document.querySelector('#game'),out=document.querySelector('#result'),w=()=>frame.contentWindow,d=()=>frame.contentDocument,s=()=>w().gameStatus?.(),v=()=>w().officeView;let reports=[],errors=[],held=new Set();
const wait=ms=>new Promise(r=>setTimeout(r,ms));function show(status='running',extra={}){out.textContent=JSON.stringify({status,reports,errors,...extra},null,2);}function check(ok,name,extra={}){if(!ok)throw Error(name);reports.push({name,...extra});show();}
async function until(fn,ms=15000){const end=performance.now()+ms;while(!fn()){if(performance.now()>end)throw Error('Timeout '+fn);await wait(30);}}
function keys(next=[]){next=new Set(next);for(const c of held)if(!next.has(c))w().dispatchEvent(new(w().KeyboardEvent)('keyup',{code:c,bubbles:true}));for(const c of next)w().dispatchEvent(new(w().KeyboardEvent)('keydown',{code:c,bubbles:true}));held=next;}
function action(){w().dispatchEvent(new(w().KeyboardEvent)('keydown',{code:'KeyE',bubbles:true}));w().dispatchEvent(new(w().KeyboardEvent)('keyup',{code:'KeyE',bubbles:true}));}
function touch(){const b=d().getElementById('interactBtn'),r=b.getBoundingClientRect();b.setPointerCapture=()=>{};b.hasPointerCapture=()=>false;b.releasePointerCapture=()=>{};for(const type of ['pointerdown','pointerup'])b.dispatchEvent(new(w().PointerEvent)(type,{pointerId:23,pointerType:'touch',button:0,clientX:r.x+r.width/2,clientY:r.y+r.height/2,bubbles:true,cancelable:true}));delete b.setPointerCapture;delete b.hasPointerCapture;delete b.releasePointerCapture;}
async function load(mobile=false){reports=[];errors=[];held.clear();show();frame.style.width=mobile?'844px':'1100px';frame.style.height=mobile?'390px':'690px';frame.src=(new URLSearchParams(location.search).has('audio')?'./audio-play.html':'./play.html')+'?t='+performance.now();await new Promise(r=>frame.addEventListener('load',r,{once:true}));await until(()=>s()&&!d().getElementById('startBtn').disabled);w().addEventListener('error',e=>errors.push(e.message));w().addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));d().getElementById('startBtn').click();await until(()=>s().started&&!s().movementLocked);action();await until(()=>s().content?.kind==='documents');}
async function run(fn){try{await fn();check(errors.length===0,'브라우저 오류 없음');show('passed',{state:s()});}catch(e){keys();show('failed',{error:e.message,state:s()});}}
// Grid route through actual space canWalk; no teleport/finish/time manipulation in flow test.
function path(tx,tz){const step=.25,cell=(x,z)=>[Math.round(x/step),Math.round(z/step)],key=(x,z)=>x+','+z,start=cell(s().position.x,s().position.z),queue=[start],parent=new Map([[key(...start),null]]);let end;
 for(let n=0;n<queue.length;n++){const [x,z]=queue[n];if(Math.hypot(x*step-tx,z*step-tz)<.3){end=[x,z];break;}for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,nz=z+dz,k=key(nx,nz);if(parent.has(k)||!v().canWalk(nx*step,nz*step))continue;parent.set(k,[x,z]);queue.push([nx,nz]);}}
 if(!end)throw Error('Unreachable '+tx+','+tz);const pts=[];for(let cur=end;cur;cur=parent.get(key(...cur)))pts.push({x:cur[0]*step,z:cur[1]*step});return pts.reverse();}
async function walk(tx,tz){const deadline=performance.now()+90000;while(Math.hypot(s().position.x-tx,s().position.z-tz)>.32){if(performance.now()>deadline)throw Error('walk timeout '+tx+','+tz);const route=path(tx,tz),target=route[Math.min(3,route.length-1)],p=s().position,c=s().camera,dx=target.x-p.x,dz=target.z-p.z,ix=dx*Math.cos(c.currentYaw)-dz*Math.sin(c.currentYaw),iz=dx*Math.sin(c.currentYaw)+dz*Math.cos(c.currentYaw),m=Math.max(Math.abs(ix),Math.abs(iz));keys([...(Math.abs(ix)>m*.4?[ix>0?'KeyD':'KeyA']:[]),...(Math.abs(iz)>m*.4?[iz>0?'KeyS':'KeyW']:[]),'ShiftLeft']);await wait(30);}keys();await wait(120);}
async function collectAll(mobile=false){for(const p of [...s().content.papers]){await walk(p.x,p.z);await until(()=>s().nearest===p.id&&!s().content.stunned);const before=s().content.collected.length;mobile?touch():action();await until(()=>s().content.collected.length===before+1);check(!v().features.papers.find(a=>a.id===p.id).model.visible,'서류와 발광 함께 제거',{id:p.id});}}
async function finish(mobile=false){await walk(0,-6.6);await until(()=>s().nearest==='office-exit'&&!s().content.stunned);mobile?touch():action();await until(()=>s().content?.doorProgress>0);check(s().content.doorAngle>0,'실제 문 열림 애니메이션');await until(()=>s().dialogue);check(s().minigameResult?.status==='success','문이 열린 후에만 finish',{metrics:s().minigameResult?.metrics});await until(()=>!d().getElementById('partResultOverlay').hidden);const t=s().timer.elapsedMs,score=d().getElementById('partResultScore').textContent;await wait(500);check(t===s().timer.elapsedMs,'결과 대기 시간 제외');check(s().chapterId==='2019','확인 전 다음 챕터 진행 없음');d().getElementById('nextPartBtn').click();d().getElementById('nextPartBtn').click();await until(()=>s().sceneId==='life-train');check(s().chapterIndex===1&&s().camera.mode==='fixed','확인 후 서울행 기차와 전용 카메라',{score});}
document.querySelector('#flow').onclick=()=>run(async()=>{await load();check(s().appearanceId==='era-office','2019 외형 유지');check(s().camera.distance===3.8&&s().camera.fov===60,'공통 카메라');await walk(0,-6.6);await until(()=>s().nearest==='office-exit'&&!s().content.stunned);action();check(!s().content.doorUnlocked&&s().content.doorProgress===0,'서류 전 문 잠금');await collectAll();check(s().content.doorUnlocked&&s().content.exitGlow,'5장 이후 출구 조명');await wait(500);check(s().chapterId==='2019'&&s().minigame,'5장 수집만으로 자동 완료 안 됨');await finish();});
document.querySelector('#mobile').onclick=()=>run(async()=>{await load(true);check(s().mobileUI,'모바일 UI');await collectAll(true);const b=d().getElementById('interactBtn').getBoundingClientRect();check(b.right<=844&&b.bottom<=390&&b.height>=44,'모바일 행동 버튼 화면 내');await finish(true);});
document.querySelector('#hit').onclick=()=>run(async()=>{await load();const c=s().content,laser=c.lasers[0];v().avatar.position.set(laser.x,.11,laser.z);await until(()=>s().content.hits>0);const hit=s(),pos=hit.position;check(hit.movementLocked&&hit.content.stunned,'피격 경직 입력 잠금');await wait(150);check(s().content.hits===hit.content.hits,'피격 무적 중 중복 감점 없음');check(v().features.reaction>0&&parseFloat(d().getElementById('officeHit').style.opacity)>0,'상체 피격 반응과 화면 효과');const push=Math.hypot(s().position.x-pos.x,s().position.z-pos.z);check(push>.02&&push<.19,'짧고 약한 안전 밀림',{distance:push});check(v().canWalk(s().position.x,s().position.z),'넉백 후 장애물 밖');d().getElementById('pauseBtn').click();const paused=s();await wait(400);check(JSON.stringify(s().content)===JSON.stringify(paused.content)&&s().timer.elapsedMs===paused.timer.elapsedMs,'피격/레이저/시간 일시정지');d().getElementById('continueBtn').click();await until(()=>!s().content.stunned&&!s().movementLocked,1200);check(!s().movementLocked,'경직 해제 입력 복구');
 const p=v().avatar.position,cam=v().camera,T=cam.position.constructor;for(const pt of [[0,0],[0,6.8],[5,6.8],[-4.8,-5.8]])for(let yaw=0;yaw<Math.PI*2;yaw+=Math.PI/4)for(const pitch of [.2618,1.25]){const target=new T(pt[0],1.4,pt[1]);cam.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*3.8,target.y+Math.sin(pitch)*3.8,target.z+Math.cos(yaw)*Math.cos(pitch)*3.8);v().resolveCamera(cam,target);check(cam.position.y<4.2&&Math.abs(cam.position.x)<6&&Math.abs(cam.position.z)<7.5,'벽/천장 카메라 보정',{yaw,pitch});} });
document.querySelector('#photo').onclick=()=>run(async()=>{await load();keys(['KeyW']);await wait(180);keys();await wait(700);d().getElementById('pauseBtn').click();d().getElementById('pauseOverlay').hidden=true;});

const extra=document.createElement('button');extra.id='jumpCheck';extra.textContent='점프 회피·백그라운드 검사';out.before(extra);
extra.onclick=()=>run(async()=>{await load();v().avatar.position.x=-1.8;v().avatar.position.z=6;await wait(80);const before=s().content.hits;keys(['Space']);keys();await until(()=>s().jump.height>.3);const h=s().content.lasers[0];v().avatar.position.x=h.x;v().avatar.position.z=h.z;await wait(100);check(s().content.hits===before&&s().jump.airborne,'실제 점프 중 바닥 레이저 회피');v().avatar.position.x=-1.8;v().avatar.position.z=6;await until(()=>!s().jump.airborne);check(v().canWalk(s().position.x,s().position.z),'착지 및 이동 가능');Object.defineProperty(d(),'hidden',{configurable:true,value:true});d().dispatchEvent(new(w().Event)('visibilitychange'));const paused=s();await wait(350);check(JSON.stringify(s().content)===JSON.stringify(paused.content)&&s().timer.elapsedMs===paused.timer.elapsedMs,'백그라운드에서 레이저/피격시간 정지');delete d().hidden;d().dispatchEvent(new(w().Event)('visibilitychange'));d().getElementById('continueBtn').click();await wait(150);check(s().timer.interrupted&&!s().timer.pauseReasons.length,'복귀 후 이어서 진행 및 interrupted');});

const geometry=document.createElement('button');geometry.id='geometry';geometry.textContent='서류·레이저 형상 검사';out.before(geometry);
geometry.onclick=()=>run(async()=>{await load();const {LASERS,laserPosition,laserSegments}=await import('./layout.js');
 check(v().features.hazards.length===2,'레이저 정확히 두 개');check(LASERS[0].width===11.4&&LASERS[1].width===14.4,'사무실 가로 11.4m / 세로 14.4m 전체 길이');
 for(const p of v().features.papers){const meshes=[];p.model.traverse(n=>{if(n.isMesh)meshes.push(n);});check(meshes.length===2&&!meshes.some(n=>n.material.transparent||n.isLight),'종이 본체와 인쇄 표면만, 바닥 후광 없음',{id:p.id});const g=meshes[0].geometry;g.computeBoundingBox();const sz=g.boundingBox.getSize(meshes[0].position.clone());check(Math.abs(sz.x-.25)<.001&&Math.abs(sz.z-.34)<.001&&Math.abs(sz.y-.005)<.001,'문서 25×34cm · 두께 5mm',{id:p.id});check(v().canWalk(p.x,p.z),'서류 위치 접근 가능',{id:p.id});}
 for(const l of LASERS){let samples=0;for(let ms=0;ms<l.period;ms+=100){const p=laserPosition(l,ms);for(const part of laserSegments(l,p))for(let t=-part.width/2+.01;t<part.width/2;t+=.1){const x=part.x+(l.axis==='x'?t:0),z=part.z+(l.axis==='z'?t:0);checkSample(v().canWalk(x,z,0),l.id,ms,x,z);samples++;}}check(true,'피격 구간이 가구/벽 밖',{axis:l.axis,samples,periodMs:l.period,thickness:l.thickness,maxSpeed:Math.PI*(l.max-l.min)/(l.period/1000)});}
 const before=s().content.lasers;await wait(250);const after=s().content.lasers;check(after[0].z!==before[0].z&&after[0].x===before[0].x,'가로 레이저 Z축 이동');check(after[1].x!==before[1].x&&after[1].z===before[1].z,'세로 레이저 X축 이동');
 function checkSample(ok,id,ms,x,z){if(!ok)throw Error('Laser furniture overlap '+JSON.stringify({id,ms,x,z}));}
});

const mobilePhoto=document.createElement('button');mobilePhoto.id='mobilePhoto';mobilePhoto.textContent='모바일 화면 캡처';out.before(mobilePhoto);mobilePhoto.onclick=()=>run(async()=>{await load(true);keys(['KeyW']);await wait(180);keys();await wait(700);d().getElementById('pauseBtn').click();d().getElementById('pauseOverlay').hidden=true;});

const continuous=document.createElement('button');continuous.id='continuous';continuous.textContent='연속선 렌더링 검사';out.before(continuous);
continuous.onclick=()=>run(async()=>{await load();const {LASERS,laserPosition,laserContact}=await import('./layout.js');
 for(const h of v().features.hazards){check(h.model.children.length===4,'각 레이저: 긴 본체/코어/후광만 사용',{id:h.id});for(const mesh of h.model.children){mesh.geometry.computeBoundingBox();const size=mesh.geometry.boundingBox.getSize(mesh.position.clone());check(Math.abs(size.x-h.width)<.001&&mesh.material.depthTest===true,'가구 마스크와 무관한 전체 길이 및 깊이 검사',{id:h.id,width:size.x});}
 const children=h.model.children.map(m=>m.uuid).join();for(let ms=0;ms<h.period;ms+=150){h.setPosition(laserPosition(h,ms));checkFixed(h,children);}check(true,'전 이동 주기에서 메시 분할/숨김/새 생성 없음',{id:h.id});}
 check(!laserContact({x:-3.2,z:2.5},LASERS[0],{x:0,z:2.5},0),'가구 내부 피격 제외 유지');check(laserContact({x:-2.2,z:3.95},LASERS[0],{x:0,z:3.95}),'책상 앞 빈 바닥 피격 유지');
 function checkFixed(h,ids){if(h.model.children.some(m=>!m.visible)||h.model.children.map(m=>m.uuid).join()!==ids||h.model.position.y!==.158)throw Error('beam discontinuity');}
});
for(const [i,p] of [[0,{x:0,z:3.7,yaw:0}],[1,{x:-1.2,z:0,yaw:-Math.PI/2}],[2,{x:1.4,z:-2,yaw:Math.PI}]]){const b=document.createElement('button');b.id='laserView'+i;b.textContent='레이저 시점 '+(i+1);out.before(b);b.onclick=()=>run(async()=>{await load();d().getElementById('pauseBtn').click();d().getElementById('pauseOverlay').hidden=true;v().avatar.position.x=p.x;v().avatar.position.z=p.z;const resolve=v().resolveCamera;v().resolveCamera=(cam,target)=>{target.set(p.x,1.4,p.z);cam.position.set(p.x+Math.sin(p.yaw)*Math.cos(Math.PI/12)*3.8,1.4+Math.sin(Math.PI/12)*3.8,p.z+Math.cos(p.yaw)*Math.cos(Math.PI/12)*3.8);resolve(cam,target);};v().features.hazards[0].setPosition({x:0,z:2.5});v().features.hazards[1].setPosition({x:3.2,z:0});await wait(150);check(true,'고정 계수의 서로 다른 위치/회전 시점',{...p});});}

export {load,run,check,until,wait,collectAll,finish,w,d,s,v,frame,out};
