const frame=document.querySelector('#game'),out=document.querySelector('#result'),w=()=>frame.contentWindow,d=()=>frame.contentDocument,s=()=>w().gameStatus?.(),audio=()=>w().trainAudioStatus?.();let checks=[],errors=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,ms=25000){const end=performance.now()+ms;while(!fn()){if(performance.now()>end)throw Error('Timeout: '+fn);await wait(20);}}
function report(status='running',extra={}){out.textContent=JSON.stringify({status,checks,errors,...extra},null,2);}function check(ok,name,data={}){if(!ok)throw Error(name);checks.push({name,...data});report();}
async function load({mobile=false,office=false}={}){frame.style.width=mobile?'844px':'1100px';frame.style.height=mobile?'390px':'690px';frame.src='./play.html?'+(office?'office&':'')+'t='+performance.now();await new Promise(r=>frame.addEventListener('load',r,{once:true}));await until(()=>s()&&!d().getElementById('startBtn').disabled);w().addEventListener('error',e=>errors.push(e.message));w().addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));d().getElementById('startBtn').click();await until(()=>s().started);}
async function run(fn){checks=[];errors=[];report();try{await fn();check(errors.length===0,'브라우저 오류 없음');report('passed',{state:s(),audio:audio(),seoul:w().seoulAudioStatus?.()});}catch(e){report('failed',{error:e.message,state:s(),audio:audio()});}}
async function seoul(){await until(()=>s().chapterId==='seoul');await until(()=>!s().timer.pauseReasons.length);check(!d().body.classList.contains('train-cutscene')&&!d().querySelector('.train-skip'),'기차 UI 정리');check(audio().voices.length===0&&!audio().entered,'기차 오디오 종료·중복 없음');await until(()=>!w().seoulAudioStatus().bgmPaused&&w().seoulAudioStatus().bgmTime>.1);check(w().seoulAudioStatus().errors.length===0,'서울 Night City 최초 진입 재생');check(s().camera.distance===3.8&&s().camera.fov===60,'공통 탐색 카메라 복귀');check(d().getElementById('partResultOverlay').hidden,'기차 점수 화면 추가 없음');}
document.querySelector('#flow').onclick=()=>run(async()=>{await load();await until(()=>s().content?.timeMs>1300);check(s().appearanceId==='era-office','2019 주인공 외형 유지');check(s().content.passengers===5,'다섯 배경 승객');check(getComputedStyle(d().getElementById('hud')).display==='none'&&getComputedStyle(d().getElementById('touchControls')).display==='none','컷신 HUD·조작 숨김');check(s().movementLocked,'컷신 이동 잠금');await until(()=>audio().counts.door===1&&audio().voices.includes('bgm')&&audio().voices.includes('ambience'));const early=s().content;check(audio().errors.length===0,'BGM·환경음·문 닫힘 재생',{counts:audio().counts});await until(()=>s().content?.timeMs>10000);check(s().content.cityBlend>.5&&s().content.nearZ!==early.nearZ&&s().content.farZ!==early.farZ,'근경·원경 이동과 도시 진입');const t=s().timer.elapsedMs,remain=15000-s().content.timeMs;await seoul();check(s().timer.elapsedMs-t>=remain-160&&s().timer.elapsedMs-t<remain+1000,'약 15초 자동 전환',{time:s().timer.elapsedMs});check(audio().counts.door===1,'문 닫힘 한 번');});
document.querySelector('#pause').onclick=()=>run(async()=>{await load();await until(()=>s().content?.timeMs>2000);d().getElementById('pauseBtn').click();await wait(80);const a=s().content,t=s().timer.elapsedMs;await wait(450);check(JSON.stringify(s().content)===JSON.stringify(a)&&s().timer.elapsedMs===t,'수동 일시정지: 장면·카메라·시간 동결');check(audio().voices.length===0,'일시정지 오디오 정지');d().getElementById('continueBtn').click();await until(()=>s().content.timeMs>a.timeMs+150&&audio().voices.includes('bgm'));d().getElementById('soundBtn').click();check(audio().muted,'공통 음소거');d().getElementById('soundBtn').click();check(!audio().muted,'공통 음소거 해제');Object.defineProperty(d(),'hidden',{value:true,configurable:true});d().dispatchEvent(new (w().Event)('visibilitychange'));await wait(80);const b=s().content;await wait(400);check(JSON.stringify(s().content)===JSON.stringify(b)&&audio().voices.length===0,'백그라운드 모방: 장면 및 소리 정지');delete d().hidden;d().dispatchEvent(new (w().Event)('visibilitychange'));d().getElementById('continueBtn').click();await until(()=>audio().voices.includes('bgm'));check(s().timer.interrupted,'중단 이력 유지');await seoul();check(audio().counts.door===1&&audio().errors.length===0,'복귀 중 중복 문 소리·오디오 오류 없음');});
document.querySelector('#skip').onclick=()=>run(async()=>{await load({mobile:true});await until(()=>s().content?.timeMs>1400);check(!d().querySelector('.train-skip')&&!w().trainView.setSequenceSkip,'건너뛰기 버튼·실행 경로 없음');const before=s().content.timeMs;for(const code of ['Space','KeyE','Escape']){w().dispatchEvent(new(w().KeyboardEvent)('keydown',{code}));w().dispatchEvent(new(w().KeyboardEvent)('keyup',{code}));}d().getElementById('dialogue').click();await wait(250);check(s().chapterId==='train'&&s().content.timeMs<before+700,'키·대사창 클릭으로 조기 종료 불가');if(d().getElementById('pauseOverlay').hidden===false)d().getElementById('continueBtn').click();await until(()=>s().chapterId==='seoul');check(s().timer.elapsedMs>=14800,'약 15초 후 자동 서울 진입');});
// Uses the existing office interaction pipeline; short waypoint fixture skips repeated navigation only.
document.querySelector('#office').onclick=()=>run(async()=>{await load({office:true});await until(()=>!s().dialogue&&!s().movementLocked);const action=()=>{w().dispatchEvent(new(w().KeyboardEvent)('keydown',{code:'KeyE'}));w().dispatchEvent(new(w().KeyboardEvent)('keyup',{code:'KeyE'}));};action();await until(()=>s().content?.kind==='documents');for(const p of w().officeView.features.papers){w().officeView.avatar.position.set(p.x,.11,p.z);await until(()=>s().nearest===p.id&&!s().content.stunned);action();await wait(60);}await until(()=>s().content.doorUnlocked);const exit=w().officeView.features.exit;w().officeView.avatar.position.set(exit.x,.11,exit.z+.6);await until(()=>s().nearest==='office-exit'&&!s().content.stunned);action();await until(()=>!d().getElementById('partResultOverlay').hidden);const total=d().getElementById('partResultScore').textContent;check(s().chapterId==='2019','2019 확인 전 기차 자동 진입 없음');d().getElementById('nextPartBtn').click();await until(()=>s().chapterId==='train');check(s().appearanceId==='era-office','2019 결과 확인 후 기존 외형으로 기차 진입',{officeScore:total});await seoul();});
for(const [i,time] of [[0,2200],[1,7800],[2,11700]])document.querySelector('#photo'+i).onclick=()=>run(async()=>{await load({mobile:i===2});await until(()=>s().content?.timeMs>=time);d().getElementById('pauseBtn').click();d().getElementById('pauseOverlay').hidden=true;check(true,'컷신 일시정지 캡처',{graphics:s().graphics,time:s().content.timeMs});});

document.querySelector('#dialogue').onclick=()=>run(async()=>{await load({office:true});const initial=s(),deadline=initial.timer.elapsedMs+initial.remainingMs;check(s().lineIndex===0&&s().remainingMs<=2500&&s().remainingMs>2000,'첫 문장 2.5초');d().getElementById('pauseBtn').click();const t=s().remainingMs;await wait(350);check(s().remainingMs===t,'일시정지 대사 시간 동결');d().getElementById('continueBtn').click();await until(()=>s().lineIndex===1);check(Math.abs(s().timer.elapsedMs-deadline)<120&&s().remainingMs<=2500,'두 번째 문장 2.5초 시점',{elapsed:s().timer.elapsedMs});await until(()=>!s().dialogue);check(Math.abs(s().timer.elapsedMs-(deadline+2500))<150,'마지막 문장도 2.5초 후 종료',{elapsed:s().timer.elapsedMs});});
